### ISSUE TITLE
сервер

### ISSUE THREAD

**Issue by Piloswine1** [vigoroous/Qchat#2]
сделай еще репозиторий под серв (я на расте тещу)

To-go:
- [ ] proper pending handle (in qml)
- [x] proper utf handling with cyrillic characters (in rust)
- [ ] discarding messages on switching server

_to be continued..._

**Comment by vigoroous** [comment]
> сделай еще репозиторий под серв (я на расте тещу)
> 
> To-go:
> 
> * [ ]  proper pending handle (in qml)
> * [ ]  proper utf handling with cyrillic characters (in rust)
> 
> _to be continued..._

Понял принял
